INSERT INTO accounts (ID, USERNAME, AMOUNT) VALUES (1, 'SMITH', 1000);
INSERT INTO accounts (ID, USERNAME, AMOUNT) VALUES (2, 'OLIVER', 2000);
INSERT INTO accounts (ID, USERNAME, AMOUNT) VALUES (3, 'MACK', 300);
INSERT INTO accounts (ID, USERNAME, AMOUNT) VALUES (4, 'PETER', 4000);